version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - ISC_CPF_MERGE_FILE=/irisdev/app/merge.cpf
    ports: 
      - 52774:52773
      - 1973:1972
    command: 
      - -a
      - iris session iris -U%SYS '##class(Security.Users).UnExpireUserPasswords("*")'
      - --check-caps false
    volumes:
      - .:/home/irisowner/irisdev
      - ./entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh